### ISSUE TITLE
Tipo de temperatura

### ISSUE THREAD

**Issue by alu0100696455** [alu0100699968/object-oriented-programming-in-js-sergio_-_jonathan#2]
Ahora mismo el conversor acepta cualquier cadena que empiece por 'c' o 'f' y la interpreta como Celsius o Fahrenheit. Hay que arreglarlo y que solo acepte prefijos de estos.

**Comment by alu0100699968** [comment]
No es necesario aceptar prefijo (confirmado por @crguezl). Solo debe aceptar el símbolo de la unidad ('C', 'F' o 'K').
